controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\forms\ContactForm;
use app\models\forms\ResetPasswordForm;
use Yii;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii2mod\rbac\filters\AccessControl;
use app\models\Contact;
use app\models\About;
use app\models\Photo;
use app\models\Product;
use app\models\Category;
use yii\data\Pagination;



/**
 * Class SiteController
 *
 * @package app\controllers
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => [
                    'login',
                    'logout',
                    'signup',
                    'request-password-reset',
                    'password-reset',
                    'account',
                ],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login', 'signup', 'request-password-reset', 'password-reset'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['logout', 'account'],
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'index' => ['get'],
                    'contact' => ['get', 'post'],
                    'account' => ['get', 'post'],
                    'login' => ['get', 'post'],
                    'logout' => ['post'],
                    'signup' => ['get', 'post'],
                    'request-password-reset' => ['get', 'post'],
                    'password-reset' => ['get', 'post'],
                    'page' => ['get', 'post'],
                ],
            ],

        ];
    }

    /**
     * @inheritdoc
     */
    public function actions(): array
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'login' => [
                'class' => 'yii2mod\user\actions\LoginAction',
            ],
            'logout' => [
                'class' => 'yii2mod\user\actions\LogoutAction',
            ],
            'signup' => [
                'class' => 'yii2mod\user\actions\SignupAction',
            ],
            'request-password-reset' => [
                'class' => 'yii2mod\user\actions\RequestPasswordResetAction',
            ],
            'password-reset' => [
                'class' => 'yii2mod\user\actions\PasswordResetAction',
            ],
            'page' => [
                'class' => 'yii2mod\cms\actions\PageAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {

        $model = new Contact();

        return $this->render('index',['model=>$model']);
    }

    /**
     * Displays contact page.
     *
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Contact();

        if ($model->load(Yii::$app->request->post())) {
           $model->created = date('Y-m-d h:m:s');
           $model->save();
           return $this->redirect(['index', 'id' => $model->id]);
       } else {
        return $this->render('index', [
            'model' => $model,
            ]);
    }
}
public function actionUpdate($id)
{
    $model = $this->findModel($id);
    $cats = Category::find()->all();

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
        return $this->redirect(['view', 'id' => $model->id]);
    } else {
        return $this->render('update', [
            'model' => $model,
            'cats' => $cats, ]);
    }
}
public function actionContact()
{
    $model = new ContactForm();

    if ($model->load(Yii::$app->request->post()) && $model->validate()) {
        $model->created = date('Y-m-d h:m:s');
        $model->save();

        Yii::$app->session->setFlash('success', Yii::t('app', 'Thank you for contacting us. We will respond to you as soon as possible.'));

        return $this->refresh();



    }else {
        Yii::$app->session->setFlash('error', Yii::t('app', 'There was an error sending email.'));
    }


    return $this->render('contact', [
        'model' => $model,
        ]);

}

    /**
     * Displays account page.
     *
     * @return string|\yii\web\Response
     */
    public function actionAccount()
    {
        $resetPasswordForm = new ResetPasswordForm(Yii::$app->user->identity);

        if ($resetPasswordForm->load(Yii::$app->request->post()) && $resetPasswordForm->resetPassword()) {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Password has been updated.'));

            return $this->refresh();
        }

        return $this->render('account', [
            'resetPasswordForm' => $resetPasswordForm,
            ]);
    }

    public function actionSearch($q = NULL)
    {
       // $this->layout = 'column2';
        if($q){
            $model = new \app\models\Search();
            $model->q = $q;
            $result = $model->search();

        }else{
            $result = [];
        }
        return $this->render('search', [
            'result' => $result
            ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
    public function actionProfnastil()
    {

       return $this->render('profnastil');

   }

    public function actionProduct()
    {
        // $model = Product::findOne($id);
        return $this->render('product', [
            // 'model' => $model,
        ]);

    }


   public function actionGalereya()
   {

       $model = new Category();
       $categories = Category::find()->all();
       $images = Photo::find()->orderBy('category_id')->all();
       return $this->render('galereya', [
           'model' => $model,
           'categories' => $categories,
           'images' => $images
           ]);


        // return $this->render('galereya');

   }

}

views/blocks/footer.php
<?php
use yii\helpers\Url;
?>

<div id="get-quote" class="bg-color black text-center">
    <div class="container">
        <div class="row get-a-quote">
            <div class="col-md-12">
                <a class="black" href="<?= Url::to('site/contact') ?>">
                  <?php if (\Yii::$app->language == 'uz'): ?>
                    Биз билан богланинг
                  <?php elseif (\Yii::$app->language == 'ru'): ?>
                    Связаться с нами
                  <?php endif; ?>
                </a>
            </div>
        </div>
        <div class="move-top bg-color page-scroll">
            <a href="#page">
                <i class="glyphicon glyphicon-arrow-up"></i>
            </a>
        </div>
    </div>
</div>
<footer id="footer">
    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-3 widget bottom-xs-pad-20">
                    <div class="widget-title">
                        <h3 class="title">
                          <?php if (\Yii::$app->language == 'ru'): ?>
                              Наши услуги
                          <?php elseif (\Yii::$app->language == 'uz'): ?>
                              Бизнинг хизматлар
                          <?php endif; ?>
                        </h3>
                    </div>
                    <nav>
                        <ul>
                            <li>
                              <?php if (\Yii::$app->language == 'ru'): ?>
                                  Обслуживание молочной фермы
                              <?php elseif (\Yii::$app->language == 'uz'): ?>
                                  Сут фермаси хизматлари
                              <?php endif; ?>
                            </li>
                        <ul>
                            <li>
                              <?php if (\Yii::$app->language == 'ru'): ?>
                                  Ввод в эксплуатацию
                              <?php elseif (\Yii::$app->language == 'uz'): ?>
                                  Ишга тушириш
                              <?php endif; ?>
                            </li>
                        <ul>
                            <li>
                              <?php if (\Yii::$app->language == 'ru'): ?>
                                  Готовые решения
                              <?php elseif (\Yii::$app->language == 'uz'): ?>
                                  Таййор ечимлар
                              <?php endif; ?>
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-3 widget bottom-xs-pad-20">
                    <div class="widget-title">
                        <h3 class="title">Адрес</h3>
                    </div>
                    <p>
                      <?php if (\Yii::$app->language == 'uz'): ?>
                          Қатортол кўч., 1А /2 уй <br>
                          Тошкент ш., Чилонзор тумани
                      <?php elseif (\Yii::$app->language == 'ru'): ?>
                          ул. Катартал, дом 1А /2 <br>
                          г. Ташкент, Чиланзарский район
                      <?php endif; ?>
                    </p>

                    </div>
                <div class="col-xs-12 col-sm-6 col-md-3 widget bottom-xs-pad-20">
                    <div class="widget-title">
                        <h3 class="title">Контакты</h3>
                    </div>
                    <p><strong> +998 (71) 276-96-91<br /> +998 (97) 773-09-99</strong></p>
                    <a class="text-color" href="mailto:gea.tashkent@gmail.com">gea.tashkent@gmail.com</a>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-3 widget">
                    <div class="widget-title">
                        <!-- Title -->
                        <h3 class="title">
                          <?php if (\Yii::$app->language == 'ru'): ?>
                            Время работы
                          <?php elseif (\Yii::$app->language == 'uz'): ?>
                            Иш вақти
                          <?php endif; ?>
                        </h3>
                    </div>
                    <nav>
                        <ul>
                            <!-- List Items -->
                            <li>
                                <?php if (\Yii::$app->language == 'ru'): ?>
                                  с 9:00 до 18:00
                                <?php elseif (\Yii::$app->language == 'uz'): ?>
                                  9:00 дан 18:00 гача
                                <?php endif; ?>
                            </li>
                            <li>
                              <?php if (\Yii::$app->language == 'uz'): ?>
                                Дам олиш кунисиз
                              <?php elseif (\Yii::$app->language == 'ru'): ?>
                                Без выходных
                              <?php endif; ?>
                            </li>
                        </ul>
                        <!-- Count -->
                        <!-- <div class="footer-count">
                            <p class="count-number" data-count="3550">total projects :
                                <span class="counter"></span>
                            </p>
                        </div>
                        <div class="footer-count">
                            <p class="count-number" data-count="2550">happy clients :
                                <span class="counter"></span>
                            </p>
                        </div> -->
                    </nav>
                </div>
     <!--            <div class="col-xs-12 col-sm-6 col-md-3 widget newsletter bottom-xs-pad-20">
                    <div class="widget-title">
                        <h3 class="title">Подписка</h3>
                    </div>
                    <div>
                        <p>Subscribe to Our Newsletter to get Important News, Amazing Offers &amp; Inside Scoops:</p>
                        <p class="form-message1"></p>
                        <div class="clearfix"></div>
                        <form id="subscribe_form" action="subscription.php" method="post" name="subscribe_form"
                              role="form">
                            <div class="input-text form-group has-feedback">
                                <input class="form-control" type="email" value="" name="subscribe_email" />
                                <button class="submit bg-color" type="submit">
                                    <span class="glyphicon glyphicon-arrow-right"></span>
                                </button></div>
                        </form>
                    </div>
                </div> -->
            </div>
        </div>
    </div>
    <!-- footer-top -->
    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6">
                    &copy; GEA-Tashkent, 2018
                </div>
            </div>
        </div>
    </div>
    <!-- footer-bottom -->
</footer>
<!-- footer -->

views/blocks/footer_sample.php
<?php ?>

<div id="get-quote" class="bg-color black text-center">
    <div class="container">
        <div class="row get-a-quote">
            <div class="col-md-12">Get A Free Quote / Need a Help ? 
                <a class="black" href="#">Contact Us</a>
            </div>
        </div>
        <div class="move-top bg-color page-scroll">
            <a href="#page">
                <i class="glyphicon glyphicon-arrow-up"></i>
            </a>
        </div>
    </div>
</div>
<!-- request -->
<footer id="footer">
    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-3 widget bottom-xs-pad-20">
                    <div class="widget-title">
                        <!-- Title -->
                        <h3 class="title">Address</h3>
                    </div>
                    <!-- Address -->
                    <p>
                        <strong>Office:</strong>ООО «Musaffo Umid»
                        <br />Пром.Зона ТХАЙ 1
                        <br />Тошкент шахри</p>
                    <!-- Email -->
                    <a class="text-color" href="mailto:info@zozothemes.com">info@tom-baraka.uz</a> 
                    <!-- Phone -->
                   <p>
                        <strong>Офис:</strong>ООО «Musaffo Umid»
                        <br />Пром.Зона ТХАЙ 1
                        <br />Тошкент шахри</p>
                    <!-- Email -->
                    <a class="text-color" href="mailto:info@tombaraka.uz">info@tombaraka.uz</a> 
                    <!-- Phone -->
                    <p></div>
                <div class="col-xs-12 col-sm-6 col-md-3 widget bottom-xs-pad-20">
                    <div class="widget-title">
                        <!-- Title -->
                        <h3 class="title">Товарлар</h3>
                    </div>
                   <nav>
                        <ul>
                            <!-- List Items -->
                            <li>
                                <a href="#">Профнастил</a>
                            </li>
                            <li>
                                <a href="#">Туникапон</a>
                            </li>
                            <li>
                                <a href="#">Сендвич панеллар</a>
                            </li>
                            <li>
                                <a href="#">Черепитца</a>
                            </li>
                            <li>
                                <a href="#">Потолокли ва фасадли копмозициялар</a>
                            </li>
                            <li>
                                <a href="#">Панжара</a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-3 widget">
                    <div class="widget-title">
                        <!-- Title -->
                        <h3 class="title">Business Hours</h3>
                    </div>
                    <nav>
                        <ul>
                            <!-- List Items -->
                            <li>
                                <a href="#">Monday-Friday: 9am to 5pm</a>
                            </li>
                            <li>
                                <a href="#">Saturday / Sunday: Closed</a>
                            </li>
                        </ul>
                        <!-- Count -->
                        <div class="footer-count">
                            <p class="count-number" data-count="3550">total projects : 
                                <span class="counter"></span>
                            </p>
                        </div>
                        <div class="footer-count">
                            <p class="count-number" data-count="2550">happy clients : 
                                <span class="counter"></span>
                            </p>
                        </div>
                    </nav>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-3 widget newsletter bottom-xs-pad-20">
                    <div class="widget-title">
                        <!-- Title -->
                        <h3 class="title">Newsletter Signup</h3>
                    </div>
                    <div>
                        <!-- Text -->
                        <p>Subscribe to Our Newsletter to get Important News, Amazing Offers &amp; Inside Scoops:</p>
                        <p class="form-message1"></p>
                        <div class="clearfix"></div>
                        <!-- Form -->
                        <form id="subscribe_form" action="subscription.php" method="post" name="subscribe_form"
                              role="form">
                            <div class="input-text form-group has-feedback">
                                <input class="form-control" type="email" value="" name="subscribe_email" /> 
                                <button class="submit bg-color" type="submit">
                                    <span class="glyphicon glyphicon-arrow-right"></span>
                                </button></div>
                        </form>
                    </div>
                    <!-- Social Links -->
                    <div class="social-icon gray-bg icons-circle i-3x">
                        <a href="#">
                            <i class="fa fa-facebook"></i>
                        </a> 
                        <a href="#">
                            <i class="fa fa-google"></i>
                        </a> 
                        </div>
                </div>
                <!-- .newsletter -->
            </div>
        </div>
    </div>
    <!-- footer-top -->
    <div class="copyright">
        <div class="container">
            <div class="row">
                <!-- Copyrights -->
                <div class="col-xs-12 col-sm-6 col-md-6">Copyright &copy; zozothemes.com., 2015
                    <br />
                    <!-- Terms Link -->

                    <a href="#">Terms of Use</a> / 
                    <a href="#">Privacy Policy</a></div>
                <div class="col-xs-12 text-center visible-xs-block page-scroll gray-bg icons-circle i-3x">
                    <!-- Goto Top -->
                    <a href="#page">
                        <i class="glyphicon glyphicon-arrow-up"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- footer-bottom -->
</footer>
<!-- footer -->

views/blocks/menu.php
<?php

use yii\helpers\Url;

use app\models\Category;
 ?>
 <!--  Navbar -->
<div class="container">

 <!-- <?= yii\bootstrap\Html::dropDownList('category_id', null, Category::all(), ['class' => 'top-bar-section top-bar-bg-light shop-top-bar']) ?> -->
 </div>
        <header class="new-version">
            <div class="container dark-header">
                <div class="row navbar navbar-default" role="navigation">
                    <div class="col-md-12">
                        <div class="navbar-header">
                            <!-- Button For Responsive toggle -->
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <!-- Navbar Collapse -->
                        <div class="navbar-collapse collapse">
                            <!-- nav -->
                            <?=\app\components\Menu::widget();?>

                            <?php /*
                                <a class='languages' href="<?= \app\components\Helper::createMultilanguageReturnUrl('uz') ?>">Ўзб </a>
                                <a class='languages' href="<?= \app\components\Helper::createMultilanguageReturnUrl('ru') ?>">Рус </a>
                                <a class='languages' href="<?= \app\components\Helper::createMultilanguageReturnUrl('en') ?>">Uzb</a>
                              */ ?>

                             <ul class="navbar-nav">
                                <li class="top-social-icon icons-hover-black">
                                    <a href="#">
                                        <i class="fa fa-facebook"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fa fa-youtube"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fa fa-rss"></i>
                                    </a>

                                    </a>
                                 </li>

                                <!-- Header Search -->
                                <li class="hidden-767">
                                    <a href="#" class="header-search">
                                        <span>
                                            <i class="fa fa-search"></i>
                                        </span>
                                    </a>
                                </li>
                            </ul>
                             <ul class="nav navbar-nav">
                                 <li class="top-parent">
                                <a href="javascript:void(0)">
                                    <?php if (Yii::$app->language == 'uz'){
                                        echo 'UZ';
                                    }else{
                                        echo 'РУ';
                                    }
                                    ?>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a  href="<?= \app\components\Helper::createMultilanguageReturnUrl('uz') ?>">
                                        <img src="<?= Yii::getAlias('@web')?>/img/uz.jpg"/>   UZ</a>
                                    </li>
                                    <li>
                                        <a  href="<?= \app\components\Helper::createMultilanguageReturnUrl('ru') ?>">
                                        <img src="<?= Yii::getAlias('@web')?>/img/ru.jpg"/>   РУ</a>
                                    </li>
                                </ul>
                            </li>
                            </ul>
                            <!-- Right nav -->
                            <!-- Header Search Content -->
                            <div class="bg-white hide-show-content no-display header-search-content">
                            <form role="search" class="navbar-form vertically-absolute-middle" action="<?= Url::to(['/site/search']) ?>">
                                    <div class="form-group">
                                        <input type="text" placeholder="<?= Yii::t('template', 'Qidirish'); ?>" class="form-control" name="q" value="" />
                                    </div>
                            </form>
                                <button class="close">
                                    <i class="fa fa-times"></i>
                                </button>
                            </div>
                            <!-- Header Search Content -->
                        </div>
                        <!-- /.navbar-collapse -->
                    </div>
                    <!-- /.col-md-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container -->

        </header>

<div id="top-bar" class="top-bar-section top-bar-bg-light shop-top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <!-- Left nav -->

                        <!-- Top Social Icon -->
                    </div>
                </div>
            </div>
        </div>

views/blocks/preheader.php
<?php

use app\components\Helper;// o`zgartirilganda o`zgarmadi
?>

<div class="new-version tb-pad-20">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="navbar-header">
                        <!-- Button For Responsive toggle -->
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span></button>
                        <!-- Logo -->
                        <a class="navbar-brand" href="<?=\Yii::$app->homeUrl?>">
                            <img class="site_logo" alt="Site Logo" src="<?= Yii::getAlias('@web')?>/img/logo.png"/>
                        </a>
                    </div>
                        <!-- Navbar Collapse -->
                        <div class="office-details">
                            <div class="detail-box">
                                <div class="icon"><i class="fa fa-phone"></i></div>
                                <div class="detail">
                                    <strong>+998 (71) 276-96-91<br>+998 (97) 773-09-99</strong>
                                    <!-- <span>
                                        <a href="mailto:gea.tashkent@gmail.com">gea.tashkent@gmail.com
</a>
                                    </span> -->
                                </div>
                            </div>
                            <div class="detail-box">
                                <div class="icon"><i class="fa fa-clock-o"></i></div>
                                <div class="detail">
                                    <strong>
                                      <?php if (\Yii::$app->language == 'uz'): ?>
                                        Иш вакти 9:00 дан 18:00 гача
                                      <?php elseif (\Yii::$app->language == 'ru'): ?>
                                        Время работы с 9:00 до 18:00
                                      <?php endif; ?>
                                    </strong>
                                    <span>
                                      <?php if (\Yii::$app->language == 'uz'): ?>
                                        Дам олишсиз ишлаймиз!
                                      <?php elseif (\Yii::$app->language == 'ru'): ?>
                                        Без выходных
                                      <?php endif; ?>
                                    </span>
                                </div>
                            </div>
                            <div class="detail-box">
                                <div class="icon"><i class="fa fa-map-marker"></i></div>
                                <div class="detail">
                                  <?php if (\Yii::$app->language == 'uz'): ?>
                                      <strong>Қатортол кўч., 1А /2 уй</strong><span> Тошкент ш., Чилонзор тумани</span>
                                  <?php elseif (\Yii::$app->language == 'ru'): ?>
                                      <strong>ул. Катартал, дом 1А /2</strong><span> г. Ташкент, Чиланзарский район</span>
                                  <?php endif; ?>
                                </div>
                            </div>


                            <div class="col-sm-4 hidden-xs">
                              <span class="top-welcome">

  <!-- <a href="<?=\app\components\Helper::createMultilanguageReturnUrl('uz') ?>">O'zb</a>
|
<a href="<?=\app\components\Helper::createMultilanguageReturnUrl('cyrl') ?>">cyrl</a>

<a href="<?=\app\components\Helper::createMultilanguageReturnUrl('ru') ?>">рус</a>
|
<a href="<?=\app\components\Helper::createMultilanguageReturnUrl('en') ?>">Eng</a>  -->
                        </span>
                    </div>



                        </div>
                        <!-- /.navbar-collapse -->
                    </div>
                    <!-- /.col-md-12 -->
                </div>
            </div>
        </div>



<!-- Top Bar --><!--
<div id="top-bar" class="top-bar-section top-bar-bg-light">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">

                <!-- Top Contact --><!--
                <div class="top-contact link-hover-black">
                    <a href="#"><i class="fa fa-phone"></i>(98)311-84-83, (98)309-71-09</a>
                    <a href="#"><i class="fa fa-envelope"></i>info@tombaraka.com</a>
                </div>

                <!-- Top Social Icon --><!--
                <div class="top-social-icon icons-hover-black">
                    <a href="#">
                        <i class="fa fa-facebook"></i>
                    </a>
                    <a href="#">
                        <i class="fa fa-twitter"></i>
                    </a>
                    <a href="#">
                        <i class="fa fa-youtube"></i>
                    </a>
                    <a href="#">
                        <i class="fa fa-rss"></i>
                    </a>
                </div>


            </div>
        </div>
    </div>
</div> -->